"""add_profile_equipment_and_injuries

Revision ID: 77faeb22af13
Revises: 9261c277946b
Create Date: 2025-12-26 21:35:27.803943

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "77faeb22af13"
down_revision: Union[str, Sequence[str], None] = "9261c277946b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column(
            "injuries",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column("user_profiles", sa.Column("load", sa.Integer(), nullable=True))
    op.add_column(
        "user_profiles",
        sa.Column(
            "training_location", sa.String(), server_default="gym", nullable=False
        ),
    )
    op.add_column(
        "user_profiles",
        sa.Column(
            "available_equipment",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "user_profiles",
        sa.Column(
            "avoid_equipment",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "user_profiles",
        sa.Column(
            "latest_scan", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("user_profiles", "weight")
    op.drop_column("user_profiles", "body_fat")
    op.drop_column("user_profiles", "height")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column(
            "height",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_profiles",
        sa.Column(
            "body_fat",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_profiles",
        sa.Column(
            "weight",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user_profiles", "latest_scan")
    op.drop_column("user_profiles", "avoid_equipment")
    op.drop_column("user_profiles", "available_equipment")
    op.drop_column("user_profiles", "training_location")
    op.drop_column("user_profiles", "load")
    op.drop_column("user_profiles", "injuries")
    # ### end Alembic commands ###
