"""mark plan_data as MutableDict

Revision ID: b86cb5a7b8e1
Revises: feb197e01c1d
Create Date: 2025-12-29 23:36:52.694058

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b86cb5a7b8e1"
down_revision: Union[str, Sequence[str], None] = "feb197e01c1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
