# Mapped based on ExerciseDB taxonomy and standard anatomy
MUSCLE_GROUPS = [
    "back",
    "calves",
    "chest",
    "forearms",
    "hips",
    "neck",
    "shoulders",
    "thighs",
    "waist",
    "hands",
    "feet",
    "face",
    "full body",
    "biceps",
    "upper arms",
    "triceps",
    "hamstrings",
    "quadriceps",
]
STANDARD_EQUIPMENT = [
    "assisted",
    "band",
    "barbell",
    "battling rope",
    "body weight",
    "bosu ball",
    "cable",
    "dumbbell",
    "ez barbell",
    "hammer",
    "kettlebell",
    "leverage machine",
    "medicine ball",
    "olympic barbell",
    "power sled",
    "resistance band",
    "roll",
    "rollball",
    "rope",
    "sled machine",
    "smith machine",
    "stability ball",
    "stick",
    "suspension",
    "trap bar",
    "vibrate plate",
    "weighted",
    "wheel roller",
]
